version: '3.8'

services:
  frontend:
    build:
      context: ./web
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NEXT_PUBLIC_API=http://host.docker.internal:8000/api
      - API=http://host.docker.internal:8000/api
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    build:
      context: ./api
    ports:
      - "8000:8000"
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=api.settings
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn --bind 0.0.0.0:8000 api.wsgi:application
      "
    networks:
      - mynetwork
networks:
  mynetwork: