# Generated by Django 5.0.6 on 2024-05-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="image_url",
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
